# Generated by Django 5.1.4 on 2024-12-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoryType",
                    models.CharField(
                        choices=[
                            ("Салаты", "Салаты"),
                            ("Рецепты первых блюд", "Рецепты первых блюд"),
                            ("Рецепты вторых блюд", "Рецепты вторых блюд"),
                            ("Дессерты", "Дессерты"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Наименование")),
                ("recipe", models.TextField(verbose_name="Рецепт")),
            ],
            options={
                "verbose_name": "Рецепты",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
